{{- if $.Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-zones"
  labels:
    app: "{{ .Release.Name }}"
    component: zone-files
spec:
  {{ toYaml .Values.persistence.volume | nindent 2 }}
{{- end -}}