# -- (string) The image to use
image: ubuntu/bind9:9.16-20.04_beta
# -- (string) The name of the registry secret to use
imagePullSecrets: null

# -- (list) Any extra files that should go into `/etc/bind/`
extraFiles:
  # -- Any additional settings for `named.conf.local`; the ACL "internals"
  # MUST remain defined, as it is used to give "AXFR" zone privileges (zone
  # transfer)
  named.conf.local: |
    //
    // Do any local configuration here
    //
     
    // Consider adding the 1918 zones here, if they are not used in your
    // organization
    //include "/etc/bind/zones.rfc1918";

    acl "internals" {
      10.0.0.0/8;
      192.168.0.0/16;
      172.16.0.0/12;
    };

# -- (list) List of TSIG keys for dynamic updates. Generate keys in BIND with this command:
# `tsig-keygen -a hmac-sha256 k8s-external-dns``
keys:
  - # -- (string) The name of the key
    name: k8s-external-dns
    # -- (string) The key algo; defaults to "hmac-sha256"
    algo: "hmac-sha256"
    # -- (string) The TSIG secret for this key
    secret: null

# -- list DNS zones (domains).
zones:
  - # -- (string) zone name
    zone: k8s.lab 
    # -- list(string) The names of keys authorized to update the zone
    keys:
      - k8s-external-dns
    # -- list(string) Any extra records you want to add for the zone. E.g. `frosty IN A 192.168.42.1`. One record per list entry.
    records: |
      - "frosty IN A 192.168.42.1"
      - "leo IN A 192.168.42.23"

# -- Service settings
service:
  # -- object Annotations to add to the service
  annotations: {}

persistence:
  # -- Set to `true` to enable persistance for zone files
  enabled: true
  # -- The data for the `PersistentVolumeClaim` for state storage. Typically you'll want to add at least a storageClassName
  volume:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100M
