# Service
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Release.Name }}-tcp"
  annotations:
    {{- $.Values.service.annotations | toYaml | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: "dns-tcp"
      protocol: TCP
      targetPort: 53
      port: 53
  selector:
    app: "{{ $.Release.Name }}"
    component: bind9
---
# Service. https://github.com/kubernetes/kubernetes/issues/23880
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Release.Name }}-udp"
  annotations:
    {{- $.Values.service.annotations | toYaml | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: "dns-udp"
      protocol: UDP
      targetPort: 53
      port: 53
  selector:
    app: "{{ $.Release.Name }}"
    component: bind9